name: minimnia_app
description: A simple app that loads minimnia.de.cool in a WebView.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1

flutter:
  uses-material-design: true